name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@30d582111533d59ab793fd9f971817241654f3ec
