name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes/kops' }}
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
